openapi: '3.0.0'
servers:
  - url: http://localhost:8080
info:
  title: customer api definition - v1
  version: 'v1'
x-wso2-basePath: /api/v1
x-wso2-production-endpoints:
  urls:
  - http://localhost:8080
paths:
  '/customer':
    get:
      responses:
        '200':
          description: ok, get all customer data
          # ERROR: response body validation always fails for the type array
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/customerSchema'
    post:
      responses:
        '200':
          description: ok, succussfully added new customer
        '500':
          description: internal server error
      # ERROR: request body validation doesn't work
      requestBody:
        $ref: '#/components/requestBodies/customerBody'
  '/customer/{customerId}':
    get:
      responses:
        '200':
          description: ok, get customer data for a given id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/customerSchema'
        '404':
          description: error, customer not found for the given id
      # ERROR: path variable validation doesn't work
      parameters:
        - in: path
          name: customerId
          required: true
          schema:
            type: integer
            format: int32
security:
  - customer_api_basic_auth: []
components:
  # basic authentication config
  securitySchemes:
    customer_api_basic_auth:
      type: http
      scheme: basic
  # request bodies
  requestBodies:
    customerBody:
      content:
        application/json:
          schema: 
            $ref: '#/components/schemas/customerSchema'
      required: true
  #schemas
  schemas:
    customerSchema:
      type: object
      required:
        - id
        - name
      properties:
        id: 
          type: integer
        name:
          type: string